categories:
  - title: "Features"
    label: "enhancement"
  - title: "Bug Fixes"
    label: "bug"
  - title: "Chores"
    labels:
      - "chore"
      - "documentation"
  - title: "Dependencies"
    label: "dependencies"
autolabeler:
  - label: "chore"
    title:
      - '/chore(?!\(deps\))/i'
  - label: "bug"
    title:
      - '/fix(?!\(deps\))/i'
  - label: "enhancement"
    title:
      - "/feat/i"
exclude-labels:
  - "changelog"
category-template: "### $TITLE"
template: |
  ## [$TAG_NAME](https://github.com/inclusive-design/idrc-cms-authenticator/compare/$PREVIOUS_TAG...$TAG_NAME)

  $CHANGES
