name: Draft release

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate version
        id: calver
        run: |
          export VERSION=$(date "+%Y.%m.%d")
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
      - uses: release-drafter/release-drafter@v6
        id: release
        with:
          tag: ${{ steps.calver.outputs.version }}
          name: ${{ steps.calver.outputs.version }}
          version: ${{ steps.calver.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ steps.release.outputs.tag_name }}
          release-notes: ${{ steps.release.outputs.body }}
          hide-release-date: true
          parse-github-usernames: true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore(release): release ${{ steps.release.outputs.tag_name }}"
          title: "chore(release): release ${{ steps.release.outputs.tag_name }}"
          branch: changelog
          labels: changelog
